server:
  # 服务器运行模式 release | debug
  # Server operating mode: release | debug
  run-mode: release
  # http-port
  # 服务器端口 - 格式为 -ip:port（绑定特定 IP）或 :port（绑定所有 IPs）
  # Server port - format: -ip:port (bind to a specific IP) or :port (bind to all IPs)
  http-port: :9000
  # 读取超时时间（秒），请求超时前等待的最大时间
  # Read timeout (seconds), maximum time to wait before request timeout
  read-timeout: 60
  # 写入超时时间（秒），写入超时前等待的最大时间
  # Write timeout (seconds), maximum time to wait before write timeout
  write-timeout: 60
  # 性能监控接口（私有 HTTP 服务器）
  # Performance monitoring interface (private HTTP server)
  private-http-listen: :9001

app:
  # 默认每页显示的项目数（分页）
  # Default number of items per page (pagination)
  default-page-size: 10
  # 最大每页允许的项目数（分页）
  # Maximum number of items allowed per page (pagination)
  max-page-size: 100
  # 应用操作的默认超时时间（秒）
  # Default timeout for application operations (seconds)
  default-context-timeout: 60

  # 临时文件存储路径
  # Temporary file storage path
  temp-path: storage/temp
  # 上传文件保存的日期路径设置 默认不设置 为 200601/02 格式 https://github.com/haierkeys/custom-image-gateway/wiki/%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E6%97%A5%E6%9C%9F%E8%B7%AF%E5%BE%84%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E
  # Date path settings for uploaded files (default: not set, format: 200601/02) https://github.com/haierkeys/custom-image-gateway/wiki/Date-Path-Format-for-Stored-Uploaded-Files
  upload-date-path: 200601/02
  # 上传文件的 URL 前缀
  # URL prefix for uploaded files
  upload-url-pre: http://192.168.215.2:9000
  # 上传文件的最大大小（单位：MB）
  # Maximum size of uploaded files (in MB)
  upload-max-size: 20
  # 允许上传的图片文件扩展名
  # Allowed image file extensions for upload
  upload-allow-exts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif
    - .tiff
    - .avif
    - .webp
  # 上传图片的最大宽度
  # Maximum width of uploaded images
  image-max-size-width: 800
  # 上传图片的最大高度
  # Maximum height of uploaded images
  image-max-size-height: 800
  # 上传图片的质量（范围：0-100）
  # Quality of uploaded images (range: 0-100)
  image-quality: 100

log:
  # 日志级别
  # Log level
  level: Debug
  # 日志文件路径
  # Log file path
  file: storage/logs/log.log
  # 是否为生产环境
  # Whether this is a production environment
  production: true

security:
  # auth-token
  # 单服务网关 Token 加密混淆 Key
  # Single-service gateway Token encryption and obfuscation key
  auth-token: 6666
  # 多用户开放网关 Token 加密混淆 Key
  # Multi-user open gateway Token encryption and obfuscation key
  auth-token-key: X-Auth-Token

# database
# 数据库配置
# Database configuration
database:
  type: sqlite
  path: storage/database/db.db
  table-prefix: pre_
  auto-migrate: true

# user
# 多用户开放网关相关配置
# Multi-user open gateway related configuration
user:
  # 多用户开放网关是否启用
  # Whether the multi-user open gateway is enabled
  is-enable: true
  # 多用户开放网关是否开启注册
  # Whether the multi-user open gateway is enabled to register
  register-is-enable: false

# 服务器本地存储配置
# server local storage configuration
local-fs:
  # 是否在 单服务网关 内启用服务器本地存储
  # Whether Server Local Storage is enabled in the single-service gateway
  is-enable: false
  # 是否在 多用户开放网关 内启用用户文件存储
  # Whether Server Local Storage is enabled in the multi-user open gateway
  is-user-enable: true
  # 是否启用内置的 HTTP 文件访问服务
  # Whether the built-in HTTP file access service is enabled
  httpfs-is-enable: true
  # 上传文件保存路径
  # Path to save uploaded files
  save-path: storage/uploads

# 阿里云 OSS 配置
# Alibaba Cloud OSS configuration
oss:
  # 是否在 单服务网关 内启用阿里云 OSS 存储
  # Whether alibaba cloud OSS storage is enabled in the single-service gateway
  is-enable: false
  # 是否在 多用户开放网关 内启用阿里云 OSS 存储
  # Whether alibaba cloud OSS storage is enabled in the multi-user open gateway
  is-user-enable: true
  # OSS 服务的 Endpoint（需要配置）
  # Endpoint for OSS service (needs configuration)
  endpoint:
  # OSS 存储桶名称（需要配置）
  # OSS bucket name (needs configuration)
  bucket-name:
  # OSS 访问密钥 ID（需要配置）
  # OSS access key ID (needs configuration)
  access-key-id:
  # OSS 访问密钥 Secret（需要配置）
  # OSS access key secret (needs configuration)
  access-key-secret:
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: blog

# CloudFlu R2 存储配置
# CloudFlu R2 storage configuration
cloudflue-r2:
  # 是否启用 R2 云存储
  # Whether R2 cloud storage is enabled
  is-enable: false
  # 是否在 多用户开放网关 内 R2 云存储
  # Whether R2 cloud storage is enabled in the multi-user open gateway
  is-user-enable: true
  # R2 存储桶名称
  # R2 bucket name
  bucket-name: image
  # R2 帐户 ID（需要配置）
  # R2 account ID (needs configuration)
  account-id:
  # R2 访问密钥 ID（需要配置）
  # R2 access key ID (needs configuration)
  access-key-id:
  # R2 访问密钥 Secret（需要配置）
  # R2 access key secret (needs configuration)
  access-key-secret:
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: blog

# AWS S3 存储配置
# AWS S3 storage configuration
aws-s3:
  # 是否在 单服务网关 内启用 AWS S3 云存储
  # Whether AWS S3 cloud storage is enabled in the single-service gateway
  is-enable: false
  # 是否在 多用户开放网关 内启用 AWS S3 云存储
  # Whether AWS S3 cloud storage is enabled in the multi-user open gateway
  is-user-enable: true
  # AWS 区域（区域代码）
  # AWS region (region code)
  region: ap-southeast-1
  # S3 存储桶名称（需要配置）
  # S3 bucket name (needs configuration)
  bucket-name:
  # S3 访问密钥 ID（需要配置）
  # S3 access key ID (needs configuration)
  access-key-id:
  # S3 访问密钥 Secret（需要配置）
  # S3 access key secret (needs configuration)
  access-key-secret:
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: blog

# MinIO 存储配置
# MinIO storage configuration
minio:
  # 是否在 单服务网关 内启用 MinIO 云存储
  # Whether MinIO cloud storage is enabled in the single-service gateway
  is-enable: true
  # 是否在 多用户开放网关 内启用 MinIO 云存储
  # Whether MinIO cloud storage is enabled in the multi-user open gateway
  is-user-enable: true
  # MinIO 服务器的 Endpoint URL
  # Endpoint URL for MinIO server
  endpoint: http://192.168.215.2:9000
  # MinIO 区域（可以自定义）
  # MinIO region (can be customized)
  region: test
  # MinIO 存储桶名称
  # MinIO bucket name
  bucket-name: image
  # MinIO 访问密钥 ID（默认值）
  # MinIO access key ID (default value)
  access-key-id: minioadmin
  # MinIO 访问密钥 Secret（默认值）
  # MinIO access key secret (default value)
  access-key-secret: minioadmin
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: blog

webdav:
  # 是否在 单服务网关 内启用 WebDAV 存储
  # Whether WebDAV storage is enabled in the single-service gateway
  is-enable: false
  # 是否在 多用户开放网关 内启用 WebDAV 存储
  # Whether WebDAV storage is enabled in the multi-user open gateway
  is-user-enable: true
  # WebDAV 服务的地址（需要配置） 例如 https://webdav.demo.com/Download/
  #WebDAV service address (to be configured) | Example: https://webdav.demo.com/Download/
  endpoint:
  # WebDAV 服务的用户名（需要配置）
  # Username for WebDAV service (needs configuration)
  user:
  # WebDAV 服务的密码（需要配置）
  # Password for WebDAV service (needs configuration)
  password:
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: demo_note

# 多吉云存储配置
# Doge Cloud storage configuration
doge:
  # 是否在 单服务网关 内启用多吉云存储
  # Whether Doge Cloud storage is enabled in the single-service gateway
  is-enable: false
  # 是否在 多用户开放网关 内启用多吉云存储
  # Whether Doge Cloud storage is enabled in the multi-user open gateway
  is-user-enable: true
  # 多吉云 S3 服务的 Endpoint URL（需要配置）例如 https://cos.ap-shanghai.myqcloud.com
  # Endpoint URL for Doge Cloud S3 service (needs configuration) e.g. https://cos.ap-shanghai.myqcloud.com
  endpoint:
  # 多吉云区域（可以自定义）
  # Doge Cloud region (can be customized)
  region: automatic
  # 多吉云存储桶名称（需要配置）
  # Doge Cloud bucket name (needs configuration)
  bucket-name:
  # 多吉云访问密钥 ID（需要配置）
  # Doge Cloud access key ID (needs configuration)
  access-key-id:
  # 多吉云访问密钥 Secret（需要配置）
  # Doge Cloud access key secret (needs configuration)
  access-key-secret:
  # 上传文件的自定义路径或前缀
  # Custom path or prefix for uploaded files
  custom-path: blog
